spring.application.name=ticket_service
spring.datasource.url=jdbc:mysql://localhost:3306/flightticketdb
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=create
spring.datasource.password=Welcome@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver